
#define REL_SYMBOLIC R_PPC64_ADDR64
#define REL_USYMBOLIC R_PPC64_UADDR64
#define REL_GOT R_PPC64_GLOB_DAT
#define REL_PLT R_PPC64_JMP_SLOT
#define REL_RELATIVE R_PPC64_RELATIVE
#define REL_COPY R_PPC64_COPY
#define REL_DTPMOD R_PPC64_DTPMOD64
#define REL_DTPOFF R_PPC64_DTPREL64
#define REL_TPOFF R_PPC64_TPREL64

#define ELFMACH EM_PPC64
