E(0, "Unknown error")
E(EAI_AGAIN, "Temporary failure in name resolution")
E(EAI_BADFLAGS, "Invalid flags")
E(EAI_FAIL    , "General failure")
E(EAI_FAMILY  , "Bad address family")
E(EAI_MEMORY  , "Out of memory")
E(EAI_NONAME  , "Name did not resolve")
E(EAI_SERVICE , "Unknown service")
E(EAI_SOCKTYPE, "Bad socket type")
E(EAI_SYSTEM  , "System call error")
E(EAI_OVERFLOW, "Overflow")
