#ifndef __INTTYPES_H
#define __INTTYPES_H

#define __NEED_wchar_t
#include <alltypes.h>
#include <features.h>
#include <stdint.h>

#define __PRI8      "hh"
#define __PRI16     "h"
#define __PRI32     ""
#define __PRI64     "ll"
#define __PRIPTR    "l"

#define __PRI_FAST8 "hh"
#define __PRI_FAST64 "ll"
#if INT_FAST16_MAX==0x7fff
#define __PRI_FAST16 "h"
#elif INT_FAST16_MAX==0x7fffffff
#define __PRI_FAST16 ""
#else
#define __PRI_FAST16 "ll"
#endif
#if INT_FAST32_MAX==0x7fffffff
#define __PRI_FAST32 ""
#else
#define __PRI_FAST32 "ll"
#endif

#define PRIb8       __PRI8  "b"
#define PRIB8       __PRI8  "B"
#define PRId8       __PRI8  "d"
#define PRIi8       __PRI8  "i"
#define PRIo8       __PRI8  "o"
#define PRIu8       __PRI8  "u"
#define PRIx8       __PRI8  "x"
#define PRIX8       __PRI8  "X"
#define PRIb16      __PRI16  "b"
#define PRIB16      __PRI16  "B"
#define PRId16      __PRI16  "d"
#define PRIi16      __PRI16  "i"
#define PRIo16      __PRI16  "o"
#define PRIu16      __PRI16  "u"
#define PRIx16      __PRI16  "x"
#define PRIX16      __PRI16  "X"
#define PRIb32      __PRI32  "b"
#define PRIB32      __PRI32  "B"
#define PRId32      __PRI32  "d"
#define PRIi32      __PRI32  "i"
#define PRIo32      __PRI32  "o"
#define PRIu32      __PRI32  "u"
#define PRIx32      __PRI32  "x"
#define PRIX32      __PRI32  "X"
#define PRIb64      __PRI64  "b"
#define PRIB64      __PRI64  "B"
#define PRId64      __PRI64  "d"
#define PRIi64      __PRI64  "i"
#define PRIo64      __PRI64  "o"
#define PRIu64      __PRI64  "u"
#define PRIx64      __PRI64  "x"
#define PRIX64      __PRI64  "X"
#define PRIbLEAST8       __PRI8  "b"
#define PRIBLEAST8       __PRI8  "B"
#define PRIdLEAST8       __PRI8  "d"
#define PRIiLEAST8       __PRI8  "i"
#define PRIoLEAST8       __PRI8  "o"
#define PRIuLEAST8       __PRI8  "u"
#define PRIxLEAST8       __PRI8  "x"
#define PRIXLEAST8       __PRI8  "X"
#define PRIbLEAST16      __PRI16  "b"
#define PRIBLEAST16      __PRI16  "B"
#define PRIdLEAST16      __PRI16  "d"
#define PRIiLEAST16      __PRI16  "i"
#define PRIoLEAST16      __PRI16  "o"
#define PRIuLEAST16      __PRI16  "u"
#define PRIxLEAST16      __PRI16  "x"
#define PRIXLEAST16      __PRI16  "X"
#define PRIbLEAST32      __PRI32  "b"
#define PRIBLEAST32      __PRI32  "B"
#define PRIdLEAST32      __PRI32  "d"
#define PRIiLEAST32      __PRI32  "i"
#define PRIoLEAST32      __PRI32  "o"
#define PRIuLEAST32      __PRI32  "u"
#define PRIxLEAST32      __PRI32  "x"
#define PRIXLEAST32      __PRI32  "X"
#define PRIbLEAST64      __PRI64  "b"
#define PRIBLEAST64      __PRI64  "B"
#define PRIdLEAST64      __PRI64  "d"
#define PRIiLEAST64      __PRI64  "i"
#define PRIoLEAST64      __PRI64  "o"
#define PRIuLEAST64      __PRI64  "u"
#define PRIxLEAST64      __PRI64  "x"
#define PRIXLEAST64      __PRI64  "X"
#define PRIbFAST8       __PRI_FAST8  "b"
#define PRIBFAST8       __PRI_FAST8  "B"
#define PRIdFAST8       __PRI_FAST8  "d"
#define PRIiFAST8       __PRI_FAST8  "i"
#define PRIoFAST8       __PRI_FAST8  "o"
#define PRIuFAST8       __PRI_FAST8  "u"
#define PRIxFAST8       __PRI_FAST8  "x"
#define PRIXFAST8       __PRI_FAST8  "X"
#define PRIbFAST16      __PRI_FAST16  "b"
#define PRIBFAST16      __PRI_FAST16  "B"
#define PRIdFAST16      __PRI_FAST16  "d"
#define PRIiFAST16      __PRI_FAST16  "i"
#define PRIoFAST16      __PRI_FAST16  "o"
#define PRIuFAST16      __PRI_FAST16  "u"
#define PRIxFAST16      __PRI_FAST16  "x"
#define PRIXFAST16      __PRI_FAST16  "X"
#define PRIbFAST32      __PRI_FAST32  "b"
#define PRIBFAST32      __PRI_FAST32  "B"
#define PRIdFAST32      __PRI_FAST32  "d"
#define PRIiFAST32      __PRI_FAST32  "i"
#define PRIoFAST32      __PRI_FAST32  "o"
#define PRIuFAST32      __PRI_FAST32  "u"
#define PRIxFAST32      __PRI_FAST32  "x"
#define PRIXFAST32      __PRI_FAST32  "X"
#define PRIbFAST64      __PRI_FAST64  "b"
#define PRIBFAST64      __PRI_FAST64  "B"
#define PRIdFAST64      __PRI_FAST64  "d"
#define PRIiFAST64      __PRI_FAST64  "i"
#define PRIoFAST64      __PRI_FAST64  "o"
#define PRIuFAST64      __PRI_FAST64  "u"
#define PRIxFAST64      __PRI_FAST64  "x"
#define PRIXFAST64      __PRI_FAST64  "X"
#define PRIbMAX64      __PRI64  "b"
#define PRIBMAX64      __PRI64  "B"
#define PRIdMAX64      __PRI64  "d"
#define PRIiMAX64      __PRI64  "i"
#define PRIoMAX64      __PRI64  "o"
#define PRIuMAX64      __PRI64  "u"
#define PRIxMAX64      __PRI64  "x"
#define PRIXMAX64      __PRI64  "X"
#define PRIbPTR64      __PRIPTR  "b"
#define PRIBPTR64      __PRIPTR  "B"
#define PRIdPTR64      __PRIPTR  "d"
#define PRIiPTR64      __PRIPTR  "i"
#define PRIoPTR64      __PRIPTR  "o"
#define PRIuPTR64      __PRIPTR  "u"
#define PRIxPTR64      __PRIPTR  "x"
#define PRIXPTR64      __PRIPTR  "X"

#define SCNb8       __PRI8  "b"
#define SCNB8       __PRI8  "B"
#define SCNd8       __PRI8  "d"
#define SCNi8       __PRI8  "i"
#define SCNo8       __PRI8  "o"
#define SCNu8       __PRI8  "u"
#define SCNx8       __PRI8  "x"
#define SCNX8       __PRI8  "X"
#define SCNb16      __PRI16  "b"
#define SCNB16      __PRI16  "B"
#define SCNd16      __PRI16  "d"
#define SCNi16      __PRI16  "i"
#define SCNo16      __PRI16  "o"
#define SCNu16      __PRI16  "u"
#define SCNx16      __PRI16  "x"
#define SCNX16      __PRI16  "X"
#define SCNb32      __PRI32  "b"
#define SCNB32      __PRI32  "B"
#define SCNd32      __PRI32  "d"
#define SCNi32      __PRI32  "i"
#define SCNo32      __PRI32  "o"
#define SCNu32      __PRI32  "u"
#define SCNx32      __PRI32  "x"
#define SCNX32      __PRI32  "X"
#define SCNb64      __PRI64  "b"
#define SCNB64      __PRI64  "B"
#define SCNd64      __PRI64  "d"
#define SCNi64      __PRI64  "i"
#define SCNo64      __PRI64  "o"
#define SCNu64      __PRI64  "u"
#define SCNx64      __PRI64  "x"
#define SCNX64      __PRI64  "X"
#define SCNbLEAST8       __PRI8  "b"
#define SCNBLEAST8       __PRI8  "B"
#define SCNdLEAST8       __PRI8  "d"
#define SCNiLEAST8       __PRI8  "i"
#define SCNoLEAST8       __PRI8  "o"
#define SCNuLEAST8       __PRI8  "u"
#define SCNxLEAST8       __PRI8  "x"
#define SCNXLEAST8       __PRI8  "X"
#define SCNbLEAST16      __PRI16  "b"
#define SCNBLEAST16      __PRI16  "B"
#define SCNdLEAST16      __PRI16  "d"
#define SCNiLEAST16      __PRI16  "i"
#define SCNoLEAST16      __PRI16  "o"
#define SCNuLEAST16      __PRI16  "u"
#define SCNxLEAST16      __PRI16  "x"
#define SCNXLEAST16      __PRI16  "X"
#define SCNbLEAST32      __PRI32  "b"
#define SCNBLEAST32      __PRI32  "B"
#define SCNdLEAST32      __PRI32  "d"
#define SCNiLEAST32      __PRI32  "i"
#define SCNoLEAST32      __PRI32  "o"
#define SCNuLEAST32      __PRI32  "u"
#define SCNxLEAST32      __PRI32  "x"
#define SCNXLEAST32      __PRI32  "X"
#define SCNbLEAST64      __PRI64  "b"
#define SCNBLEAST64      __PRI64  "B"
#define SCNdLEAST64      __PRI64  "d"
#define SCNiLEAST64      __PRI64  "i"
#define SCNoLEAST64      __PRI64  "o"
#define SCNuLEAST64      __PRI64  "u"
#define SCNxLEAST64      __PRI64  "x"
#define SCNXLEAST64      __PRI64  "X"
#define SCNbFAST8       __PRI_FAST8  "b"
#define SCNBFAST8       __PRI_FAST8  "B"
#define SCNdFAST8       __PRI_FAST8  "d"
#define SCNiFAST8       __PRI_FAST8  "i"
#define SCNoFAST8       __PRI_FAST8  "o"
#define SCNuFAST8       __PRI_FAST8  "u"
#define SCNxFAST8       __PRI_FAST8  "x"
#define SCNXFAST8       __PRI_FAST8  "X"
#define SCNbFAST16      __PRI_FAST16  "b"
#define SCNBFAST16      __PRI_FAST16  "B"
#define SCNdFAST16      __PRI_FAST16  "d"
#define SCNiFAST16      __PRI_FAST16  "i"
#define SCNoFAST16      __PRI_FAST16  "o"
#define SCNuFAST16      __PRI_FAST16  "u"
#define SCNxFAST16      __PRI_FAST16  "x"
#define SCNXFAST16      __PRI_FAST16  "X"
#define SCNbFAST32      __PRI_FAST32  "b"
#define SCNBFAST32      __PRI_FAST32  "B"
#define SCNdFAST32      __PRI_FAST32  "d"
#define SCNiFAST32      __PRI_FAST32  "i"
#define SCNoFAST32      __PRI_FAST32  "o"
#define SCNuFAST32      __PRI_FAST32  "u"
#define SCNxFAST32      __PRI_FAST32  "x"
#define SCNXFAST32      __PRI_FAST32  "X"
#define SCNbFAST64      __PRI_FAST64  "b"
#define SCNBFAST64      __PRI_FAST64  "B"
#define SCNdFAST64      __PRI_FAST64  "d"
#define SCNiFAST64      __PRI_FAST64  "i"
#define SCNoFAST64      __PRI_FAST64  "o"
#define SCNuFAST64      __PRI_FAST64  "u"
#define SCNxFAST64      __PRI_FAST64  "x"
#define SCNXFAST64      __PRI_FAST64  "X"
#define SCNbMAX64      __PRI64  "b"
#define SCNBMAX64      __PRI64  "B"
#define SCNdMAX64      __PRI64  "d"
#define SCNiMAX64      __PRI64  "i"
#define SCNoMAX64      __PRI64  "o"
#define SCNuMAX64      __PRI64  "u"
#define SCNxMAX64      __PRI64  "x"
#define SCNXMAX64      __PRI64  "X"
#define SCNbPTR64      __PRIPTR  "b"
#define SCNBPTR64      __PRIPTR  "B"
#define SCNdPTR64      __PRIPTR  "d"
#define SCNiPTR64      __PRIPTR  "i"
#define SCNoPTR64      __PRIPTR  "o"
#define SCNuPTR64      __PRIPTR  "u"
#define SCNxPTR64      __PRIPTR  "x"
#define SCNXPTR64      __PRIPTR  "X"


#ifdef __cplusplus
extern "C" {
#endif

typedef struct { intmax_t quot, rem; } imaxdiv_t;
intmax_t imaxabs(intmax_t);
imaxdiv_t imaxdiv(intmax_t, intmax_t);
intmax_t strtoimax(const char *__restrict, char **__restrict, int);
uintmax_t strtoumax(const char *__restrict, char **__restrict, int);
intmax_t wcstoimax(const wchar_t *__restrict, wchar_t **__restrict, int);
uintmax_t wcstoumax(const wchar_t *__restrict, wchar_t **__restrict, int);

#ifdef __cplusplus
}
#endif
#endif
