#define REL_SYMBOLIC R_PPC_ADDR32
#define REL_USYMBOLIC R_PPC_UADDR32
#define REL_GOT R_PPC_GLOB_DAT
#define REL_PLT R_PPC_JMP_SLOT
#define REL_RELATIVE R_PPC_RELATIVE
#define REL_COPY R_PPC_COPY
#define REL_DTPMOD R_PPC_DTPMOD32
#define REL_DTPOFF R_PPC_DTPREL32
#define REL_TPOFF R_PPC_TPREL32

#define ELFMACH EM_PPC
